version: 2.0
environment:
jobs:

  deploy-develop:
    docker:
      - image: fzavalia/eb-cli
    steps:
      - checkout
      - run: eb deploy curriculum-vitae-develop

  deploy-prod:
    docker:
      - image: fzavalia/eb-cli
    steps:
      - checkout
      - run: eb deploy curriculum-vitae

workflows:
  version: 2
  deploy:
    jobs:

      - deploy-develop:
          filters:
            branches:
              only:
                - develop

      - deploy-prod-approval:
          type: approval
          filters:
            branches:
              only:
                - master
                
      - deploy-prod:
          requires:
            - deploy-prod-approval
          filters:
            branches:
              only:
                - master
