version: 2.0
environment:
jobs:
  build:
    docker:
      - image: docker:dind
    steps:
      - run:
          name: Build Image
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker build -t $DOCKER_REPOSITORY/curriculum:latest .
            docker push $DOCKER_REPOSITORY/curriculum:latest .
