version: 2

jobs:
  deploy:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "5f:c9:e9:ef:90:9e:0c:e1:0a:33:7f:0e:22:83:a6:7f"
      - run: ssh $EC2_HOST ./deploy.sh

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master 
