version: 2.0
environment:
jobs:

  deploy:
    docker:
      - image: fzavalia/eb-cli
    steps:
      - checkout
      - run: ~/.local/bin/eb deploy curriculum-vitae-$CIRCLE_BRANCH

  deploy-prod:
    docker:
      - image: fzavalia/eb-cli
    steps:
      - checkout
      - run: ~/.local/bin/eb deploy curriculum-vitae-$CIRCLE_BRANCH

workflows:
  version: 2
  deploy:
    jobs:

      - deploy:
          filters:
            branches:
              only:
                - develop
                - master

      - deploy-prod-approval:
          type: approval
          requires:
            - deploy
          filters:
            branches:
              only:
                - master
                
      - deploy-prod:
          requires:
            - deploy-prod-approval
          filters:
            branches:
              only:
                - master
