version: 2.0
environment:
jobs:
  deploy:
    docker:
      - image: alpine:3.8
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            apk add python3 curl git
            curl -O https://bootstrap.pypa.io/get-pip.py
            python3 get-pip.py --user
            export PATH=/root/.local/bin:$PATH
            pip --version
            pip install awsebcli --upgrade --user
            eb --version
            eb deploy curriculum-vitae-$CIRCLE_BRANCH
workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - develop
                - master