version: 2.0
environment:
jobs:

  deploy-develop:
    docker:
      - image: fzavalia/eb-cli
    steps:
      - checkout
      - run: eb deploy curriculum-vitae-develop

  deploy-prod:
    docker:
      - image: fzavalia/eb-cli
    steps:
      - checkout
      - run: eb deploy curriculum-vitae

workflows:
  version: 2
  deploy:
    jobs:

      - deploy-develop:
          filters:
            branches:
              only:
                - develop
                
      - deploy-prod:
          filters:
            branches:
              only:
                - master
