version: 2.0
environment:
jobs:
  deploy:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Install EB CLI
          command: |
            pip install awsebcli --upgrade --user
      - run:
          name: Deploy
          command: |
            ~/.local/bin/eb deploy

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - develop
                - master
