version: 2.0
environment:
jobs:
  deploy:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Install EB CLI
          command: |
            pip install awsebcli --upgrade --user
      - run:
          name: Deploy
          command: |
            ~/.local/bin/eb deploy curriculum-vitae-$CIRCLE_BRANCH
  deploy-prod:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Install EB CLI
          command: |
            pip install awsebcli --upgrade --user
      - run:
          name: Deploy
          command: |
            ~/.local/bin/eb deploy curriculum-vitae
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - develop
                - master
      - hold:
          type: approval
          requires:
            - deploy
          filters:
            branches:
              only:
                - master
      - deploy-prod:
          filters:
            branches:
              only:
                - master
