version: 2.0
environment:
jobs:
  build:
    docker:
      - image: alpine:3.8
    steps:
      - checkout
      - run: |
          apk add python3 curl
          curl -O https://bootstrap.pypa.io/get-pip.py
          python3 get-pip.py --user
          export PATH="~/.local/bin":$PATH
          pip install awsebcli --upgrade --user
            
